stratum-mining/stratumprotocol.org

src/implementation.md
src/index.md

Not sure if this is getting used but I like this site way more than the Braiins page.
1. Rewrote the index.md page removing the ipsum dolor.
2. Rewrote the implementation.md page getting the most recent info from the Braiiins page, updated the descriptions to improve grammar and understanding, fixed the left side contents bar to match the subheadings and not show "technical details" and "motivation & Impact" subsections

Site Updates - index.md & implementation.md

---

src/.vuepress/public/assets/blockchain.svg
src/.vuepress/public/assets/compare.svg
src/.vuepress/public/assets/padlock.svg
src/.vuepress/public/assets/speaker.svg
src/.vuepress/public/assets/speedometer.svg
src/.vuepress/theme/components/NavLinks.vue
src/.vuepress/theme/layouts/DocumentationLayout.vue
src/.vuepress/theme/layouts/HomeLayout.vue
src/index.md
tailwind.config.js

Fixes #21 
Added this section to the home page based on the Figma design and removed the old outdated content.
Screenshot:

Add why section to landing page

---

src/.vuepress/public/assets/arrow-right.svg
src/.vuepress/theme/components/PrimaryLink.vue
src/.vuepress/theme/layouts/HomeLayout.vue
src/index.md

Hero updates

---

src/.vuepress/theme/components/SecondaryLink.vue
src/.vuepress/theme/layouts/HomeLayout.vue
src/index.md

New footer

---

src/.vuepress/theme/components/Link.vue
src/.vuepress/theme/components/NavLink.vue
src/.vuepress/theme/components/PrimaryLink.vue
src/.vuepress/theme/components/SecondaryLink.vue
src/.vuepress/theme/layouts/HomeLayout.vue
src/index.md

improving links + fixing some urls

---

src/.vuepress/theme/layouts/HomeLayout.vue

remove right side nav on home layout

---

src/.vuepress/theme/layouts/HomeLayout.vue

fix feature grid + some ui adjustements to match figma mock up

---

src/index.md

alphabetically sort logos

---

src/index.md

Roadmap add box 5 content

---

src/index.md

This PR makes our text beautiful thanks to Ken.
Co-Authored-By: spiralbeakedtoucan <70726704+sqcken@users.noreply.github.com>

Revise copy

---

src/features.md
src/implementation.md

Moved the copy I wrote previously into "Features", matching the https://braiins.com/stratum-v2 organization, and wrote summaries of the roles and sub-protocols for "Implementation.md"

implementation and features rewrites

---

src/index.md

Just a minor tweak to make sure we emphasise that this is the reference implementation, and since we still don't have all the components, technically it would be inaccurate calling it complete, at least for now.
Feedback form @moneyball

update intro paragraph

---

src/.vuepress/theme/layouts/HomeLayout.vue

adjust why section icon size

---

src/.vuepress/theme/layouts/HomeLayout.vue
tailwind.config.js

adjust headline

---

src/.vuepress/theme/layouts/HomeLayout.vue

Add more x padding on landing sections for mobile consistency

---

src/index.md

fixes #57 and also brings back previous copy from #79  which somehow got overwritten.

Update into paragraph copy and add email as a CTA

---

src/specification.md

Changes heading sizes on specification page to show up in the sidebar.

changes heading sizes in spec to show up on sidebar

---

src/.vuepress/theme/components/Navbar.vue

Make docs header smaller height

---

src/.vuepress/theme/components/Tabs.vue
src/.vuepress/theme/layouts/HomeLayout.vue
src/index.md
tailwind.config.js

feat(home): add tabs to home layout to choose displayed conf visual

---

src/.vuepress/theme/layouts/HomeLayout.vue

fix(home): adjust decorative element position

---

src/.vuepress/theme/layouts/HomeLayout.vue
src/index.md

feat(home): add category selection in supporters section.

---

src/.vuepress/theme/layouts/HomeLayout.vue
src/index.md

fix(home): add configuration title

---

src/index.md

fix(home): replace github cta by documentation cta

---

src/.vuepress/theme/components/RoadMapSection.vue
src/.vuepress/theme/layouts/HomeLayout.vue
src/index.md

feat(home): add specification authors section

---

src/.vuepress/config.js
src/.vuepress/theme/components/NavLink.vue
src/.vuepress/theme/components/NavLinks.vue
src/.vuepress/theme/components/Navbar.vue
src/.vuepress/theme/components/Sidebar.vue
src/.vuepress/theme/layouts/DocumentationLayout.vue
src/.vuepress/theme/layouts/HomeLayout.vue

feat(core): improve navigation bar

---

src/index.md

removing due to lack of clarity if it's proper or not

remove a1 config

---

src/.vuepress/styles/index.styl

Signed-off-by: Abhijay Jain [Abhijay007j@gmail.com](mailto:Abhijay007j@gmail.com)
Fixes: #146 
Fixed image responsiveness throughout the site for different SVGs by defining universal styles in `index.styl`

(Fix) : fixed image responsiveness

---

src/index.md

change CTA

---

src/.vuepress/config.js

re-arrange the menu

---

package.json
src/.vuepress/config.js
src/.vuepress/styles/index.styl
yarn.lock

Add copy to code box

---

src/.vuepress/config.js

Until there is no actual content, let's remove it from the navigation.

Hide blog for now

---

src/_blog/StratumV2-JN-Announcement.md

Fix video link

---

src/index.md

Improve copy to avoid ambiguity and prepare it for `Job Declaration`

---

src/getting-started.md

tp sync instructions

---

src/getting-started.md

getting started on testnet4

---

app/routes/_index.tsx
app/src/components/sections/LatencyComparison.tsx

**closes #253**
Includes layout adjustments to improve responsiveness:
* Modified grid configurations in the `index` and `LatencyComparison` components.
* Also Fixed card misalignment issue when screen width shrinks to a really small size (see image below).

adjust grid layout for performance section and latency comparison

---

app/routes/developers.tsx
app/src/_developers/getting-started.md
app/src/components/Navigation.tsx
public/_redirects

- Move getting-started.md from _blog to _developers directory
- Create dedicated developers page with proper routing
- Add developers data structure and build script
- Update navigation to reflect new organization
- Configure redirects for seamless URL migration
- Update submodule reference to latest specification
Closes issue #266

feat: move getting-started guide from blog to developers section
